Реализация Accordion
js-tasks-ru/htmlcss-20240614_aynur-zaynullin pull request #4
Opened 2024-06-23 22:31 UTC by aynzayn

- Описал компонент Аккордион
- Немного стилизовал пример
![localhost](https://github.com/js-tasks-ru/htmlcss-20240614_aynur-zaynullin/assets/5789801/9c4a71e8-a6cd-49eb-affb-52003e138d94)

2024-06-23 22:31 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-24 13:27 UTC, GSemikozov requested changes

2024-06-24 13:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-family: 'Roboto', Inter, sans-serif;
у summary - Inter

2024-06-24 13:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: var(--padding-v, 24px);
в открытом состоянии 32

2024-06-24 13:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 var(--padding-h, 32px);
сверху должен быть отступ от тайтла 16px

2024-06-24 20:41 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-24 20:43 UTC, aynzayn commented on 03-lection1/02-accordion/accordion.css
> +    font-family: 'Roboto', Inter, sans-serif;
Исправил

2024-06-24 20:43 UTC, aynzayn commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: var(--padding-v, 24px);
Переделал

2024-06-24 20:43 UTC, aynzayn commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 var(--padding-h, 32px);
Переделал

2024-06-24 20:46 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-06-29 05:30 UTC, GSemikozov approved these changes

2024-06-29 05:31 UTC, merged