Модалка
js-tasks-ru/htmlcss-20240614_aynur-zaynullin pull request #9
Opened 2024-08-04 22:27 UTC by aynzayn

![image](https://github.com/user-attachments/assets/10b930d6-91be-45f3-8021-80608fd96b75)

2024-08-04 22:27 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-08-25 18:49 UTC, GSemikozov requested changes

2024-08-25 18:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +﻿.button__modal {
это не часть блока Модалка

2024-08-25 18:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal::backdrop {
если добавить модалку например на Главную, в любое место, например после карточек - это открывается и работает корректно?

2025-07-21 15:31 UTC, closed without merging